let pendingFiles = [], reloadAfterUploadClose = false;
const partSize = 5 * 1024 * 1024;
const bytes = value => value < 1024 ? `${value} B` : value < 1048576 ? `${(value / 1024).toFixed(1)} KB` : `${(value / 1048576).toFixed(1)} MB`;
const escape = value => String(value).replace(/[&<>"']/g, char => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
window.handleFileSelect = input => { addFiles([...input.files]); input.value = ''; };
window.handleDrop = event => { event.preventDefault(); event.currentTarget.classList.remove('dragover'); addFiles([...event.dataTransfer.files]); };
function addFiles(files) { files.forEach(file => { if (!pendingFiles.some(item => item.name === file.name && item.size === file.size)) pendingFiles.push(file); }); renderFiles(); }
window.removeFile = index => { pendingFiles.splice(index, 1); renderFiles(); };
function renderFiles() { const list = document.getElementById('fileList'); if (!list) return; list.innerHTML = pendingFiles.map((file, index) => `<div class="upload-item" id="upload-item-${index}"><div class="min-w-0 flex-1"><div class="flex justify-between gap-3"><span class="truncate text-sm font-semibold">${escape(file.name)}</span><span class="shrink-0 text-xs text-slate-500">${bytes(file.size)}</span></div><div class="progress hidden" id="progress-bar-wrap-${index}"><div class="progress-bar" id="progress-bar-${index}" style="width:0%"></div></div><div class="mt-1 hidden text-xs text-slate-500" id="progress-text-${index}"></div></div><button class="text-bad-500" onclick="removeFile(${index})" aria-label="Remove ${escape(file.name)}">×</button></div>`).join(''); }
window.resetUploadModal = () => { reloadAfterUploadClose = false; pendingFiles = []; renderFiles(); document.getElementById('overallProgressArea').classList.add('hidden'); document.getElementById('startUploadBtn').disabled = false; };
window.prepareNextUploadBatch = () => window.resetUploadModal();
window.startUpload = async () => { if (!pendingFiles.length) return window.showToast('Please select at least one file.', 'warning'); const button = document.getElementById('startUploadBtn'); button.disabled = true; document.getElementById('overallProgressArea').classList.remove('hidden'); let uploaded = 0, succeeded = 0, failed = 0; const total = pendingFiles.reduce((sum, file) => sum + file.size, 0); for (let index = 0; index < pendingFiles.length; index++) { const file = pendingFiles[index], bar = document.getElementById(`progress-bar-${index}`), wrap = document.getElementById(`progress-bar-wrap-${index}`), text = document.getElementById(`progress-text-${index}`); wrap.classList.remove('hidden'); text.classList.remove('hidden'); const progress = loaded => { bar.style.width = `${Math.round(loaded / file.size * 100)}%`; text.textContent = `${bytes(loaded)} / ${bytes(file.size)}`; const percentage = Math.round((uploaded + loaded) / total * 100); document.getElementById('overallProgressBar').style.width = `${percentage}%`; document.getElementById('overallStatus').textContent = `${percentage}% — ${bytes(uploaded + loaded)} / ${bytes(total)}`; }; try { const key = window.PREFIX ? `${window.PREFIX.endsWith('/') ? window.PREFIX : `${window.PREFIX}/`}${file.name}` : file.name; if (file.size <= partSize) await simpleUpload(file, progress); else await multipartUpload(file, key, progress); uploaded += file.size; succeeded++; text.textContent = 'Done'; } catch (error) { failed++; text.textContent = `Failed: ${error.message}`; window.showToast(`Failed to upload ${file.name}: ${error.message}`, 'danger'); } } document.getElementById('overallStatus').textContent = failed ? `Upload finished: ${succeeded} succeeded, ${failed} failed` : `Upload complete: ${succeeded} file(s)`; button.disabled = false; document.getElementById('uploadAnotherBtn').classList.remove('hidden'); reloadAfterUploadClose = succeeded > 0; };
function simpleUpload(file, progress) { return new Promise((resolve, reject) => { const xhr = new XMLHttpRequest(), form = new FormData(); form.append('file', file, file.name); xhr.upload.onprogress = event => { if (event.lengthComputable) progress(event.loaded); }; xhr.onload = () => xhr.status >= 200 && xhr.status < 300 ? resolve() : reject(Error(`HTTP ${xhr.status}`)); xhr.onerror = () => reject(Error('Network error')); xhr.open('POST', `/api/buckets/${encodeURIComponent(window.BUCKET)}/objects/upload?prefix=${encodeURIComponent(window.PREFIX || '')}`); setCsrfHeader(xhr); xhr.send(form); }); }
async function multipartUpload(file, key, progress) { const init = await apiFetch(`/api/buckets/${encodeURIComponent(window.BUCKET)}/multipart/initiate?key=${encodeURIComponent(key)}&contentType=${encodeURIComponent(file.type || 'application/octet-stream')}`, {method:'POST'}); if (!init.ok) throw Error('Failed to initiate multipart upload'); const {uploadId} = await init.json(), parts = []; let loaded = 0; for (let number = 1; number <= Math.ceil(file.size / partSize); number++) { const blob = file.slice((number - 1) * partSize, Math.min(number * partSize, file.size)); const eTag = await uploadPart(key, uploadId, number, blob, amount => progress(loaded + amount)); loaded += blob.size; parts.push({partNumber:number,eTag}); } const done = await apiFetch(`/api/buckets/${encodeURIComponent(window.BUCKET)}/multipart/complete?key=${encodeURIComponent(key)}`, {method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({uploadId,parts})}); if (!done.ok) throw Error('Failed to complete multipart upload'); }
function uploadPart(key, uploadId, part, blob, progress) { return new Promise((resolve, reject) => { const xhr = new XMLHttpRequest(); xhr.upload.onprogress = event => { if(event.lengthComputable) progress(event.loaded); }; xhr.onload = () => xhr.status >= 200 && xhr.status < 300 ? resolve(JSON.parse(xhr.responseText).eTag) : reject(Error(`HTTP ${xhr.status}`)); xhr.onerror = () => reject(Error('Network error')); xhr.open('PUT', `/api/buckets/${encodeURIComponent(window.BUCKET)}/multipart/part?key=${encodeURIComponent(key)}&uploadId=${encodeURIComponent(uploadId)}&partNumber=${part}`); setCsrfHeader(xhr); xhr.setRequestHeader('Content-Type','application/octet-stream'); xhr.send(blob); }); }
function setCsrfHeader(xhr) { const token=window.csrfToken?.(); if(token) xhr.setRequestHeader('X-XSRF-TOKEN',token); }
document.addEventListener('s3webui:dialogclosed', event => { if (event.target.id === 'uploadModal' && reloadAfterUploadClose) location.reload(); });
